-- Databases & schemas (Task 13). Idempotent DDL.
CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE SCHEMA   IF NOT EXISTS RAW_DB.NORTHWIND;
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB;
CREATE SCHEMA   IF NOT EXISTS ANALYTICS_DB.STAGING;
CREATE SCHEMA   IF NOT EXISTS ANALYTICS_DB.MARTS;
CREATE SCHEMA   IF NOT EXISTS ANALYTICS_DB.SNAPSHOTS;
CREATE DATABASE IF NOT EXISTS DEV_DB;   -- local dbt work
