--  Access control: functional roles
--  Implements the "better access control" business requirement.
--
--  Roles      : LOADER, TRANSFORMER, REPORTER  (each rolled up into SYSADMIN)
--  Boundaries : LOADER      -> write RAW_DB
--               TRANSFORMER -> read RAW_DB, write ANALYTICS_DB
--               REPORTER    -> read MARTS only
--  Users      : one SERVICE user per role (key-pair auth, TYPE = SERVICE)

-- SECURITYADMIN has MANAGE GRANTS account-wide, so it can create roles and
-- grant privileges on the RAW_DB/ANALYTICS_DB objects even though it doesn't
-- own them (they're created under SYSADMIN in 01_databases.sql/02_warehouses.sql).
USE ROLE SECURITYADMIN;

-- ----------------------------------------------------------------------------
-- 1. Create the functional roles
-- ----------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS LOADER      COMMENT = 'Writes raw source data into RAW_DB';
CREATE ROLE IF NOT EXISTS TRANSFORMER COMMENT = 'Reads RAW_DB, builds models in ANALYTICS_DB';
CREATE ROLE IF NOT EXISTS REPORTER    COMMENT = 'Read-only consumer of the MARTS layer';
-- Roll every functional role up into SYSADMIN 
GRANT ROLE LOADER      TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE REPORTER    TO ROLE SYSADMIN;
 
-- ----------------------------------------------------------------------------
-- 2. LOADER  ->  write RAW_DB
-- ----------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE LOADING_WH        TO ROLE LOADER;
GRANT USAGE ON DATABASE  RAW_DB            TO ROLE LOADER;
GRANT USAGE ON SCHEMA    RAW_DB.NORTHWIND  TO ROLE LOADER;

-- Objects a loader needs to stand up (COPY / Snowpipe workflows).
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA RAW_DB.NORTHWIND TO ROLE LOADER;

-- Write on current and future tables in RAW.
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL    TABLES IN SCHEMA RAW_DB.NORTHWIND TO ROLE LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA RAW_DB.NORTHWIND TO ROLE LOADER;

-- ----------------------------------------------------------------------------
-- 3. TRANSFORMER  ->  read RAW, write ANALYTICS
-- ----------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE TRANSFORM_WH   TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE  RAW_DB         TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE  ANALYTICS_DB   TO ROLE TRANSFORMER;


-- Grant Read-only Access to RAW.
GRANT USAGE  ON SCHEMA RAW_DB.NORTHWIND                     TO ROLE TRANSFORMER;
GRANT SELECT ON ALL    TABLES IN SCHEMA RAW_DB.NORTHWIND    TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.NORTHWIND    TO ROLE TRANSFORMER;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA RAW_DB.NORTHWIND    TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RAW_DB.NORTHWIND    TO ROLE TRANSFORMER;

-- Grant Write Access to STAGING for the transformer role
GRANT USAGE ON SCHEMA ANALYTICS_DB.STAGING    TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_DB.STAGING TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL   TABLES IN SCHEMA ANALYTICS_DB.STAGING TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.STAGING TO ROLE TRANSFORMER;
GRANT SELECT ON ALL    VIEWS IN SCHEMA ANALYTICS_DB.STAGING TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.STAGING TO ROLE TRANSFORMER;

-- Grant write access to MARTS for the transformer role
GRANT USAGE ON SCHEMA ANALYTICS_DB.MARTS    TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_DB.MARTS TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL   TABLES IN SCHEMA ANALYTICS_DB.MARTS TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.MARTS TO ROLE TRANSFORMER;
GRANT SELECT ON ALL    VIEWS IN SCHEMA ANALYTICS_DB.MARTS TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.MARTS TO ROLE TRANSFORMER;

--Grant write access to SNAPSHOTS for the transformer role
GRANT USAGE ON SCHEMA ANALYTICS_DB.SNAPSHOTS TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ANALYTICS_DB.SNAPSHOTS TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL   TABLES IN SCHEMA ANALYTICS_DB.SNAPSHOTS TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.SNAPSHOTS TO ROLE TRANSFORMER;

-- ----------------------------------------------------------------------------
-- 4. REPORTER  ->  read MARTS only
-- ----------------------------------------------------------------------------
-- Note: ANALYTICS_DB USAGE is granted, but REPORTER gets no schema-level
-- USAGE on RAW_DB.NORTHWIND or ANALYTICS_DB.STAGING/SNAPSHOTS, so it can't
-- see into those schemas. "Only" is enforced by omission, not a deny grant.
GRANT USAGE ON WAREHOUSE TRANSFORM_WH      TO ROLE REPORTER;
GRANT USAGE ON DATABASE  ANALYTICS_DB      TO ROLE REPORTER;

GRANT USAGE  ON SCHEMA ANALYTICS_DB.MARTS                   TO ROLE REPORTER;
GRANT SELECT ON ALL    TABLES IN SCHEMA ANALYTICS_DB.MARTS  TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.MARTS  TO ROLE REPORTER;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA ANALYTICS_DB.MARTS  TO ROLE REPORTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS_DB.MARTS  TO ROLE REPORTER;

-- ----------------------------------------------------------------------------
-- 5. One service user per role
--    TYPE = SERVICE: no password / no MFA, authenticates via key-pair 
-- ----------------------------------------------------------------------------
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS LOADER_USER
  TYPE = SERVICE
  DEFAULT_ROLE      = LOADER
  DEFAULT_WAREHOUSE = LOADING_WH
  RSA_PUBLIC_KEY    = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwT389092qelzELxaeYy04q+bSeCYHj+sSg8HI/Y/5Udyz2ba4/iazCkigxpxLnIfSp+gaAXLsLP9cBJZ5Q1KXvk1NrOvZr/9u4mZMCJYFliQio2Zz7JFfVNH6BnVFOvNFFu3NIRcopedl8CCx74X2vO/PHn997GEc+DAGCX1W2symk9QQYZxBSmivWfjthyxWfrsX16HGdsznVPQELbkFxL4+QAEgBPwPihUQn3HZ7YmfUk/14AoZYqs1ZPiwOJT3mx8d10eoeKdkf333xYMBu7qIl8mQri65Ir1myLrjectZwmKubT/OWM7Ise9exrKIw1dirAI+8kvI+FGVBUp8wIDAQAB'
  COMMENT = 'Service account for the ingestion / LOADER pipeline';

CREATE USER IF NOT EXISTS TRANSFORMER_USER
  TYPE = SERVICE
  DEFAULT_ROLE      = TRANSFORMER
  DEFAULT_WAREHOUSE = TRANSFORM_WH
  RSA_PUBLIC_KEY    = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi4XmGCTtUxpx3yTZgOwPQcUuCzSOHDvqKHB6vksqdQSxRlFWGwvAn9bGrCCjCdQ5cdZgfsNz6Ii8Tt0iRd1cySXhUILkNsYK589a6CEtkfYk9DZmxcYM4mrvvRqyMoVJH5i0CF6n19dHQ5EQLpaA6Zuc9+Oi6PsnB/RhXt5yqL8mBU1dQCf07mhf+C8IB0gTgKZ0Y/cPP4fBKF7qAQwuRjYI0ht0mi5G/kQ61aapFRx/VAOl48bsg9A2vMc+x9Jo99Hyn6Zao66uipEy2+RCI2e+mg1iDB+dy3+7RIsCUTnon+UNDudsev1tTmX4rRKJDLJNDjFPXcjRQ8jo3lJEdwIDAQAB'
  COMMENT = 'Service account for dbt / transformation runs';

CREATE USER IF NOT EXISTS REPORTER_USER
  TYPE = SERVICE
  DEFAULT_ROLE      = REPORTER
  DEFAULT_WAREHOUSE = TRANSFORM_WH
  RSA_PUBLIC_KEY    = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxCubRJlZ2Jlryb7zWOw7qbNYmOx4YfvMdxtiIeQieM8irD7HPU4puyF2U5+UkwuRTnViQ4lXylJ27Wn6/dYvMfHYxILhOTq8BjBYmHj2FdUZK5LoWrvXVevZPteOlrQf2m05+i4jt3f1zsrX/3WqC6X2MuuyXzviVMU+FrSi0IGFt1yr5PgTgRPsjW/xjWrOMD2Vm3+CLsn+5D+rCw+HSgqQs5ndE5FlKVerJVx/cf2ChMkZj5h2Y9Uo4yytxPRx3QNumPkrxBt6HsMXukqJwPscIV3WpNF8GVv5nRAe+rU1vR2K7+EU+NBQiDu5n1w5mSvRmV4Ml/fiOZnelCg7rQIDAQAB'
  COMMENT = 'Service account for BI tool / reporting connection';

-- Bind each service user to exactly its own role.
USE ROLE SECURITYADMIN;
GRANT ROLE LOADER      TO USER LOADER_USER;
GRANT ROLE TRANSFORMER TO USER TRANSFORMER_USER;
GRANT ROLE REPORTER    TO USER REPORTER_USER;


-- ----------------------------------------------------------------------------
-- 6. Verify (run to inspect the result)
-- ----------------------------------------------------------------------------
-- SHOW GRANTS TO ROLE LOADER;
-- SHOW GRANTS TO ROLE TRANSFORMER;
-- SHOW GRANTS TO ROLE REPORTER;